# Generated by Django 3.0.3 on 2020-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nis', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('kontak', models.CharField(default='-', max_length=50)),
                ('jurusan', models.CharField(default='-', max_length=50)),
                ('fakultas', models.CharField(default='-', max_length=50)),
                ('univ', models.CharField(default='-', max_length=50)),
                ('jalur', models.CharField(default='-', max_length=50)),
                ('skor_1', models.CharField(default='-', max_length=50)),
                ('skor_2', models.CharField(default='-', max_length=50)),
                ('tahunlulus', models.CharField(default='-', max_length=50)),
                ('tahunmasuk', models.CharField(default='-', max_length=50)),
                ('refrensi', models.CharField(default='-', max_length=50)),
                ('pesan', models.TextField(default='-', max_length=200)),
            ],
        ),
    ]
