# Generated by Django 3.0.3 on 2020-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='-', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fakultas',
            field=models.CharField(default='-', max_length=50, verbose_name='Fakultas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jalur',
            field=models.CharField(default='-', max_length=50, verbose_name='Jalur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jurusan',
            field=models.CharField(default='-', max_length=50, verbose_name='Jurusan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kontak',
            field=models.CharField(default='-', max_length=50, verbose_name='Kontak'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nis',
            field=models.IntegerField(verbose_name='Nis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pesan',
            field=models.TextField(default='-', max_length=200, verbose_name='Pesan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refrensi',
            field=models.CharField(default='-', max_length=50, verbose_name='Refrensi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skor_1',
            field=models.CharField(default='-', max_length=50, verbose_name='Skor 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skor_2',
            field=models.CharField(default='-', max_length=50, verbose_name='Skor 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahunlulus',
            field=models.CharField(default='-', max_length=50, verbose_name='Tauhun Lulus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahunmasuk',
            field=models.CharField(default='-', max_length=50, verbose_name='Tahum Masuk'),
        ),
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.CharField(default='-', max_length=50, verbose_name='Universitas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
