# Generated by Django 3.0.3 on 2020-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200312_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto'),
        ),
    ]
