# Generated by Django 3.0.3 on 2020-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200317_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguruanTinggi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
    ]
