# Generated by Django 3.0.3 on 2020-03-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_perguruantinggi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refrensi',
            field=models.TextField(default='-', max_length=200, verbose_name='Refrensi'),
        ),
    ]
